# Generated by Django 5.0.6 on 2024-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='leasdate',
            field=models.DateField(default=None),
        ),
    ]
