# Generated by Django 4.2.3 on 2024-03-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_owner_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='admin',
            new_name='manager',
        ),
    ]
