# Generated by Django 4.2.3 on 2024-03-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_admin_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
            preserve_default=False,
        ),
    ]
