# Generated by Django 5.0.6 on 2024-05-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_servicetype_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.manager'),
            preserve_default=False,
        ),
    ]
